### ISSUE TITLE
patch for roundcube version 1.0.1

### ISSUE THREAD

**Issue by ghost** [gianlucagiacometti/Roundcube-Purge#3]
I have posted a patch for the purge plugin at https://dl.dropboxusercontent.com/u/41489105/update_to_v1.0.1.patch

The path is on a freshly pulled clone, to apply it clone the project and place the patch in the root folder and run
patch -p1 < update_to_v1.0.1.patch

You will want to edit purgefolders.php before testing it and setting it up on the cron

**Comment by gianlucagiacometti** [comment]
Hi,
thank you for your patch suggestions. I took some of them.
You are in the costributor list now.
G
